# Generated by Django 5.2 on 2025-12-01 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openrouter", "OpenRouter"),
                            ("litellm", "LiteLLM"),
                            ("local", "Local"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("context_window", models.IntegerField(default=4096)),
                ("max_tokens", models.IntegerField(default=4096)),
                (
                    "input_price",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "output_price",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("is_available", models.BooleanField(default=True)),
                ("is_local", models.BooleanField(default=False)),
                ("requires_gpu", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("avg_response_time", models.FloatField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System Metrics",
                "verbose_name_plural": "System Metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ModelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_cost_per_day",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                ("auto_fallback_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fallback_models",
                    models.ManyToManyField(
                        blank=True, related_name="fallback_for", to="gateway.aimodel"
                    ),
                ),
                (
                    "preferred_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gateway.aimodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Preference",
                "verbose_name_plural": "Model Preferences",
            },
        ),
        migrations.CreateModel(
            name="ModelUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "response_time",
                    models.FloatField(help_text="Response time in seconds"),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="gateway.aimodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gateway_mod_user_id_0a5f3c_idx",
                    ),
                    models.Index(
                        fields=["model", "-created_at"],
                        name="gateway_mod_model_i_7e7fae_idx",
                    ),
                ],
            },
        ),
    ]
