# Generated by Django 5.2 on 2025-12-01 04:59

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=files.models.upload_to)),
                ("original_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FileQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("model", models.CharField(max_length=100)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="files.fileupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="AI-generated summary of the file"),
                ),
                (
                    "insights",
                    models.JSONField(default=list, help_text="List of key insights"),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Extracted metadata"),
                ),
                (
                    "analysis_model",
                    models.CharField(
                        help_text="Model used for analysis", max_length=100
                    ),
                ),
                (
                    "analysis_time",
                    models.FloatField(help_text="Time taken for analysis in seconds"),
                ),
                ("token_count", models.IntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="files.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Analysis",
                "verbose_name_plural": "File Analyses",
            },
        ),
    ]
